authors = ["jonas peitz <jonaspeitz@proton.me>"]
description = "Syntax highlighting for Odin"
id = "odin"
name = "Odin"
repository = "https://github.com/jpx40/zed-odin"
schema_version = 1
version = "0.0.1"

[grammars.odin]
commit = "05984368e605c852cf4fa11c51e77c6aef0bd3d1"
repository = "https://github.com/laytan/odin-tree-sitter"
